cgroup:
    automount:
        enabled: false
    hostRoot: /sys/fs/cgroup
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
rollOutCiliumPods: true
localRedirectPolicy: true
autoDirectNodeRoutes: true
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
loadBalancer:
    algorithm: maglev
    mode: dsr
l7Proxy: true
routingMode: native
devices: eth+
ipam:
    mode: kubernetes
ipv4NativeRoutingCIDR: 10.240.0.0/16
ipv6NativeRoutingCIDR: fd41:074e:1368::/48
ipv6:
    enabled: true
externalIPs:
    enabled: true
operator:
    replicas: 1
nodeIPAM:
    enabled: true
securityContext:
    capabilities:
        ciliumAgent:
            - CHOWN
            - KILL
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
        cleanCiliumState:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
