---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-csr-approver
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/pikaviestin/kube-cluster.git
      path: kubernetes/apps/kube-system/kubelet-csr-approver
      targetRevision: main
      ref: repo
    - repoURL: https://postfinance.github.io/kubelet-csr-approver
      chart: kubelet-csr-approver
      targetRevision: 1.2.5
      helm:
        releaseName: kubelet-csr-approver
        valueFiles:
          - $repo/kubernetes/apps/kube-system/kubelet-csr-approver/values.yaml
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true