---
creation_rules:
  - path_regex: bootstrap/talos/*\.sops\.ya?ml
    key_groups:
      - pgp:
          - 90F388ADD3E186B00A1D77855CBFF29F9005BCE1
  - path_regex: kubernetes/.*\.sops\.ya?ml
    # encrypted_regex: "^(data|stringData)$"
    key_groups:
      - pgp:
          - 90F388ADD3E186B00A1D77855CBFF29F9005BCE1
          - 0B73D696CC987471233E921F2C78BFEB5E80B183 # ArgoCD's key