apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - secret-generator.yaml

resources:
  - letsencrypt-production.yaml
  - letsencrypt-staging.yaml
  - cert-manager-bind-kapsi-secret.sops.yaml