apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: yllapito+acme@pikaviestin.fi
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
         rfc2136:
           nameserver: 91.232.154.53
           tsigkeyName: pikaviestink8s
           tsigAlgorithm: HMACSHA512
           tsigSecretSecretRef:
             name: cert-manager-bind-kapsi-secret
             key: secret
        selector:
          dnsZones:
            - pikaviestin.fi