apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yllapito+acme@pikaviestin.fi
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          rfc2136:
            nameserver: 91.232.154.53
            tsigKeyName: pikaviestin-k8s
            tsigAlgorithm: HMACSHA256
            tsigSecretSecretRef:
              name: cert-manager-bind-kapsi-secret
              key: secret
        selector:
          dnsZones:
            - pikaviestin.fi